# Generated by Django 4.1.5 on 2023-02-02 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ropa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('prenda', models.CharField(choices=[('camisas', 'Camisas'), ('zapatos', 'Zapatos'), ('pantalones', 'Pantalones'), ('boxer', 'Boxer'), ('pulseras', 'Pulseras'), ('gorras', 'Gorras'), ('hoodies', 'Hoodies')], default='hoodies', max_length=15)),
                ('marca', models.CharField(max_length=40)),
                ('precio', models.IntegerField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('contactoTLF', models.IntegerField()),
                ('email_contacto', models.EmailField(max_length=254)),
                ('imagenPrenda', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['usuario', '-fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('fechaComentario', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='App.ropa')),
            ],
            options={
                'ordering': ['-fechaComentario'],
            },
        ),
    ]
