# Generated by Django 4.1.5 on 2023-02-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ropa',
            name='imagenPrenda',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
    ]
